### ISSUE TITLE
Bug Report - Randomly sending error messages

### ISSUE THREAD

**Issue by Nefomemes** [Nefomemes/Fortress#26]
**Describe the bug**
The bot randomly sends an error message.

**To Reproduce**
Trigger the messageUpdate event, but make sure the message is already gone.

**Expected behavior**
The bot should not respond with an error message.

**Actual behaviour**
The bot responds with an error message.

**Screenshots**
![Screenshot_20201026-214941_Discord.jpg](https://user-images.githubusercontent.com/66000635/97187934-89a99f80-17d5-11eb-9953-84d4140d76df.jpg)

**Version**
0.0.4 (stable) it's the original repo / bot

**Why is this a bug?**
I forgot to put a measures that will only run the rest of the handler if it was a messages content update.

**Additional context**
``` 
DiscordAPIError: Unknown Message
    at RequestHandler.execute (/home/runner/Kylebot/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'get',
  path: '/channels/751305925964333124/messages/770231809401159680',
  code: 10008,
  httpStatus: 404
}
```

**Comment by Nefomemes** [comment]
I think I have addressed this in an old commiy and it's not happening anymore.
